### ISSUE TITLE
`ReadWord` equivalence bug

### ISSUE THREAD

**Issue by d-xo** [ethereum/hevm#401]
The result of simplifying the following expression is reported as non-equivalent by the smt solver:

```
(ReadWord (Lit 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff) (ConcreteBuf "\163\179s\141\183\197fx\128d'Z\ETX\173\b\ESC`\v\155\141\DC3\SO\DLE\211,\237l\255g\132D\223\&6\218"))
```

To reproduce add the following as a top level function to test.hs and call it from the repl:

```haskell
repro = do
  let p = (ReadWord (Lit 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff) (ConcreteBuf "\163\179s\141\183\197fx\128d'Z\ETX\173\b\ESC`\v\155\141\DC3\SO\DLE\211,\237l\255g\132D\223\&6\218"))
  let simplified = Expr.simplify p
  print simplified
  checkEquiv simplified p
```

**Comment by msooseth** [comment]
Another one to trigger a variation of this:

```
a = (ReadWord (Lit 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff) (ConcreteBuf "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"))
runEnv defaultEnv $ checkEquiv  a (Expr.simplify a)
```

(this was another issue I added, accidentally)

**Comment by msooseth** [comment]
One fix we discussed is to limit memory to 64b. I think 32b would make more sense. But either way, it's not easy, I think. My thoughts:
* `CopySlice` & "`ReadWord`+`WriteWord` combo" rewrites would need to take into account that the offset wraps around.
* Perhaps some other rewrites would also need to be adjusted
* Long-term easy-to-support setup would be to have a new e.g. `Lit64b` (or `Lit32b`). But that would make a mess of `Expr` because now we have two types of `Lit`. Otherwise it may be easy to miss a wraparound check in our rewrites.

**Comment by blishko** [comment]
Apparently,  `evmtool` does not implement wrap-around semantics.
Trying to deal with this at the SMT level (prevent the wrap-around semantics, which is natural for SMT bit-vectors) would require too much effort and would unnecessary complicate the encoding.
It is not worth it given that such cases should not occur in the real-world contracts.

The fuzzer has been modified to not generate such expressions: #598.
