### ISSUE TITLE
Error: unable to parse: .../out/Base.sol/CommonBase.json

### ISSUE THREAD

**Issue by iirekm** [ethereum/hevm#491]
I'm getting `Error: unable to parse: .../out/Base.sol/CommonBase.json`.

Reproduction: just followed the steps from https://hevm.dev/install.html 
- `curl -L https://foundry.paradigm.xyz | bash`
- `foundryup`
- `forge init demo` - a simple project is created
- `forge build`
- `hvm test` - `Error: unable to parse: .../out/Base.sol/CommonBase.json`

Versions: recent version of `hevm` and `forge` at time of writing.

**Comment by iirekm** [comment]
Any progress with it? It makes hevm useless for me. How are you able to use it if it clearly fails even in clean environment!

**Comment by msooseth** [comment]
I'm sorry for being late at answering. This is due to a new/old version of foundry. The JSON has changed. It's very annoying. Can you maybe use the nix setup that's explained on the README? That contains the correct foundry that will produce the JSON that hevm expects.

Please note that even though we are aware of this issue, there's little we can do -- either we break hevm for everyone using the old JSON, or we break it for everyone using the new JSON. Implementing/supporting both is a lot of pain. If you use the nix setup that's on the README, it'll use the correct version of foundry and you'll be good.

I'm sorry for the inconvenience this has caused :(

**Comment by msooseth** [comment]
Hi,

If using the new foundry, this is not an issue. So I am closing, because I don't think it's a good idea to support both old and new foundry. Let me know if you have any trouble using the new foundry!!

Cheers,

Mate

**Comment by Silur** [comment]
can you please specify what does "new foundry" mean in this case?
Because the issue persists with the current latest version `forge 0.2.0 (af97b2c 2024-07-18T00:17:45.244496253Z)`

**Comment by msooseth** [comment]
I am fixing this, sorry. Once https://github.com/ethereum/hevm/pull/510 iis merged, this will work. In the meanwhile, you can use that version, if you like! Sorry about this mess, my mistake.
